---
title: "Multiple comparisons"
author: "FGCZ"
date: "30/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r loadpackages}

library(msigdbr)
library(readr)
library(fgsea)
library(tidyverse)
library(fgcz.gsea.ora)

maxNES_threshold <- 1.8
```


```{r}
files <- unzip("rankFiles.zip", list = TRUE)
allrnk <- vector(mode = "list", length = length(files$Name))

for (i in 1:length(files$Name)) {
  tmp <- read_tsv(unz("rankFiles.zip",files$Name[i]), col_names = FALSE)
  ranks <- tmp$X2
  names(ranks) <- tmp$X1
  allrnk[[i]] <- ranks
}
names(allrnk) <- files$Name

```


```{r loadPackages}
species <- "Drosophila melanogaster"
C5 <- msigdbr_collections() %>% filter(gs_cat == "C5")
C5 <- msigdbr_collections() %>% filter(gs_cat == "C2")

```



```{r makefgseaGensetfrom_msidbr}
getMsigdbGenesets <- function(msigCollection){
  genesetsC5 <- vector(mode = "list", length = nrow(msigCollection) )
  for (i in 1:nrow(msigCollection)) {
    genesetsC5[[i]] <- msigdbr(species = species,
                               category = msigCollection$gs_cat[i],
                               subcategory = msigCollection$gs_subcat[i])
  }
  names(genesetsC5) <- make.names(msigCollection$gs_subcat)
  fgseaGSlist <- lapply(genesetsC5 , fgsea_msigdb)
  return(fgseaGSlist)
}

fgseaGSlist <- getMsigdbGenesets(C5)
i <- 5
print(names(fgseaGSlist)[i])
fgseaGS <- fgseaGSlist[[i]]

```


```{r runGSEAAnalysis}

# @param allrnk - list of rank arrays 
# @param geneset 
runGSEA_for_allContrasts <- function(allrnk,
                                     geneSet,
                                     minSize =5, maxSize = 500){
  fgseaRes <- vector(mode = "list", length = length(allrnk))
  for (i in 1:length(allrnk)) {
   message( paste( names(allrnk)[i],"\n" ) )
    fgseaRes[[i]] <- fgsea::fgsea(pathways = geneSet,
                           stats    = allrnk[[i]],
                           nperm = 1000,
                           minSize  = minSize,
                           maxSize  = maxSize)
    
  }
  
  for (i in 1:length(allrnk)) {
    fgseaRes[[i]]$comparison <- names(allrnk)[i]
  }
  return(fgseaRes)
}

fgseaRes <- runGSEA_for_allContrasts(allrnk,fgseaGS)

```


```{r integrateData, fig.cap = "Histogram of adjusted p-value." }
all <- bind_rows(fgseaRes)
all <- all %>%
  dplyr::relocate(nMoreExtreme, pval,  ES, leadingEdge, .after = size) %>%
  dplyr::relocate(comparison ,.before = pathway)

fgseaResultsForAllContrasts <- paste0("Geneset_",names(fgseaGSlist)[i],"allContrasts.xlsx")
writexl::write_xlsx(all, path = fgseaResultsForAllContrasts)
hist(all$padj)

```

```{r fig.cap="Histogram of normalized enrichment score."}
hist(all$NES)
xx <- tidyr::pivot_wider(all, id_cols = "pathway", names_from = "comparison" , values_from  = "NES")
```


```{r prepheat, fig.cap="Maximum normalized enrichment score for all comparisons."}
xm <- xx %>% dplyr::select(-pathway) %>% as.matrix
rownames(xm) <- xx$pathway


maxNES <- apply(xm, 1, function(x) {
  max(abs(x), na.rm = TRUE)
})

hist(maxNES, main = "distribution of NES")

xm <- xm[maxNES > maxNES_threshold, ]
maxNES <- maxNES[maxNES > maxNES_threshold]
xm <- xm[order(maxNES),]
maxNES <- maxNES[order(maxNES)]
p <- pheatmap::pheatmap(na.omit(xm), silent = TRUE, cluster_rows = FALSE)

```

```{r makeheatmap, fig.cap = "All comparisons", fig.height=20, fig.width=10}
print(p)
```

```{r prepheat2, fig.cap = "Maximum normalized enrichment score for contrasts involving Ctrl."}
xm <- xm[, grepl("Ctrl", colnames(xm))]
maxNES <- apply(xm, 1, function(x) {
  max(abs(x), na.rm = TRUE)
})

hist(maxNES)
xm <- xm[maxNES > maxNES_threshold, ]
maxNES <- maxNES[maxNES > maxNES_threshold]
xm <- xm[order(maxNES),]

p <- pheatmap::pheatmap(na.omit(xm), silent = TRUE, cluster_rows = FALSE)

```



```{r heatmapCtrl, fig.cap="Only vs control", fig.width=10, fig.height=15}
print(p)
```

