---
title: "Visualize single GSEA result"
author: "Witold Wolski"
date: "03/12/2020"
output: html_document
param:
  GSEAResults
---

```{r setup, include=FALSE, echo=FALSE}
library(DT)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r setupData}
#GSEAex1 <- list(
#msigDBGS = ,
#fgseaResult = fgseaRes[[1]],
#geneSet = fgseaGS[[1]],
#rankList = allrnk[[1]])
#usethis::use_data(GSEAex1)

library(fgcz.gsea.ora)
library(DT)
library(fgsea)

fgseaResult <- GSEAex1$fgseaRes
geneSet <- GSEAex1$geneSet
rankList <- GSEAex1$rankList
relevantResult <- fgseaResult %>% dplyr::filter(pval < 0.01)
```


```{r pval , fig.cap = "Volcano Plot. Panel A : -log10(p-value) vs normalized enrichment score (NES). Panel B : -log10(FDR) vs normalized enrichment score (NES)."}
par(mfrow = c(1,2))
plot(fgseaResult$NES, -log10(fgseaResult$pval),
     ylim = c(0, max(c(-log10(0.05), -log10(fgseaResult$pval)))),
     ylab = "-log10(pval)", xlab = "NES", pch = 16)
abline(h = -log10(c(0.05,0.01)), col = c(2,3))

plot(fgseaResult$NES, -log10(fgseaResult$padj),
     ylim = c(0, max(c(-log10(0.05), -log10(fgseaResult$padj)))),
     ylab = "-log10(padj)", xlab = "NES", pch = 16)
abline(h = -log10(c(0.05,0.01)), col = c(2,3))
```





```{r collapsePathway}
relevantResult <- relevantResult %>%
  dplyr::relocate(nMoreExtreme , pval ,  ES  , leadingEdge, .after = size) %>%
  dplyr::relocate(comparison ,.before = pathway)
DT::datatable(relevantResult, caption = "All Pathways")

```


```{r showPathways2}
collapsedPathways <- collapsePathways(relevantResult,
                                      geneSet, rankList)
mainPathways <- fgseaResult %>% dplyr::filter(pathway %in% collapsedPathways$mainPathways)
DT::datatable(mainPathways, caption = "Non redundant pathways created using collapsePathways.")
```


```{r plotGenesets, fig.width=20, fig.height=40, fig.cap="Protein positions in ranked list for non-redundant Pathways"}

mainGeneSets <- geneSet[mainPathways$pathway]
plotGseaTable(mainGeneSets, rankList , mainPathways,
              gseaParam = 0.5)

```
