---
title: "Visualize single GSEA result"
author: "FGCZ protinf@fgcz.uzh.ch"
date: "03/12/2020"
output: html_document
param:
  GSEAResults
---

```{r setup, include=FALSE, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r setupData}
library(DT)
library(prora)


gseaResult <- GSEAResults$fgseaRes
geneSet <- GSEAResults$geneSet
rankList <- GSEAResults$rankList
relevantResult <- GSEAResults$relevantResult
gsName <- GSEAResults$gsName
threshold <- GSEAResults$threshold
mainPathways <- GSEAResults$mainPathways
map_summaries <- GSEAResults$map_summaries
score <- GSEAResults$score
```

- Analysis for gene set category: `r gsName`.
- The filtering of gene sets used is: `r paste0("padj < ", threshold)`.
- out of `r map_summaries$nrow_all` Proteins,  `r map_summaries$nrow_mapped` were mapped to Entrez Gene identifiers.
- Proteins were ordered using the `r score`.


```{r ranklist , fig.cap = "Sorted list of proteins."}
plot(sort(rankList,decreasing = TRUE), type = "h", ylab = score)

```


```{r pval , fig.cap = " Panel B : -log10(FDR) vs normalized enrichment score (NES)."}
par(mfrow = c(1,2))


plot( fgseaResult$NES ,
     -log10(fgseaResult$padj),
     ylim = c(0, max(c(-log10(0.05), -log10(fgseaResult$padj)), na.rm = TRUE)),
     ylab = "-log10(FDR)", xlab = "NES", pch = 16, main = "")
abline(h = -log10(threshold), col = c(2,3))
```



```{r collapsePathway}
caption <- paste0("All Pathways with padj < ", threshold, ".")
DT::datatable(relevantResult, caption = caption) %>% 
  formatSignif('NES',2) %>%
  formatSignif(c('pval','padj'),2)

```


```{r showPathways2}
caption = paste0("Non redundant pathways with padj < ",  threshold,".")
DT::datatable(mainPathways, caption = caption) %>%
  formatSignif('NES',2) %>%
  formatSignif(c('pval','padj'),2)


```


```{r plotGenesets, fig.width=20, fig.height=40, fig.cap="Protein positions in ranked list for non-redundant Pathways"}

mainGeneSets <- geneSet[mainPathways$pathway]
plotGseaTable(mainGeneSets, rankList , mainPathways,
              gseaParam = 0.5)

```

Please contact `wew@fgcz.ethz.ch`
