#' Examplary Uniprot IDs
#'
#' Gene symbols for running examples to produce GPS repositories using \code{\link{makeGPS_wrappR}}
#'
#' @docType data
#' @name exampleUniprotIDs
#' @usage data(exampleUniprotIDs)
#' @format A character vector containing 2292 Uniprot IDs
NULL

#' Exemplary GPS table
#'
#' GPS table linking GOID, pathway name and genes
#' \itemize{
#'   \item \code{pathwayId.} Pathway identifier, in this case a gene ontology id
#'   \item \code{pathwayName.} Name of the pathway
#'   \item \code{gene.} Gene symbol
#' }
#'
#' @docType data
#' @name GPStab
#' @usage data(GPStab)
#' @format A data frame containing 20957 rows and 3 variables
NULL

#' Exemplary GSEA output
#'
#' GSEA output from the \code{run_GSEA.R} script provided in the \code{inst/RunScripts/} directory
#'
#' \itemize{
#'   \item \code{organism.} The organism used in the analysis
#'   \item \code{target.} Target database
#'   \item \code{outputDir.} Output directory of where the results are stores
#'   \item \code{input_data.} Input data containing gene symbols and effect estimates
#'   \item \code{GSEA_res.} Results from \code{{WebGestaltR::WebGestaltR}}
#' }
#'
#' @docType data
#' @name GSEA
#' @usage data(GSEA)
#' @format A list containing the 5 entries as described below.
NULL

#' Exemplary sigora output
#'
#' sigora output from the \code{\link{sigoraWrappR}} function containing the following entries
#'
#' \itemize{
#'   \item \code{sigora.} Result table from \code{{sigora::sigora}}
#'   \item \code{ora.} Result table from \code{{sigora::ora}}
#'   \item \code{fc_threshold.} fold change threshold used for the analysis
#'   \item \code{GPSrepository.} GPS repository used for the analysis, generated by \code{\link{makeGPS_wrappR}}
#'   \item \code{database.} Target database
#'   \item \code{data.} Original input data
#'   \item \code{proteinsAfterFiltering.} The number of proteins meeting the fold change threshold
#' }
#'
#' @docType data
#' @name sigora_example
#' @usage data(sigora_example)
#' @format A list containing 7 entries as described below
NULL

#' Exemplary WebGestaltR output
#'
#' Examplary clustering plus ora output using the \code{WebGestaltR} package.
#'
#' @docType data
#' @name webGestaltExample
#' @usage data(webGestaltExample)
#' @format A list of 12 entries
NULL

#' Contrast effect estimates
#'
#' Example data set containing effect estimates and p values from different contrasts.
#'
#' @docType data
#' @name contrast_data_example
#' @usage data(exampleContrastData)
#' @format A \code{data.frame} with 2304 rows and 18 variables
NULL
