---
title: "Order 22513"
author: "Witold Wolski"
date: "12/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE )
```

## R Markdown

```{r}
library(tidyverse)
library(prolfqua)
tmp <- prolfqua::tidyMQ_Peptides("O_22513/1789482.zip")

annot <- tmp %>% dplyr::select("raw.file") %>% distinct() %>% tidyr::separate(raw.file , c("date","run_Id","sample_Id","timepoint"), remove = FALSE) 


annot$timeN <- as.numeric(as.factor(annot$timepoint))
annot <- dplyr::select(annot, raw.file,run_Id, timepoint, timeN )
prolfqua::table_facade(arrange(annot, timeN), caption = "annotation")
writexl::write_xlsx(annot, path = "O_22513/annotation.xlsx")
```


```{r}
config <- create_config_MQ_peptide()
config$table$factors[["timeN"]] = "timeN"
config$table$factors[["time"]] = "timepoint"
config$table$factors[["run_Id"]] = "run_Id"

data <- inner_join(annot, tmp)
sdata <- setup_analysis(data, config)
lfqd <- LFQData$new(sdata, config)
lfqd$remove_small_intensities()
```

# Normalize Data and estimate protein intensities

```{r fig.cap = "Distribution of protein intensities for all samples."}

if (FALSE) {
  outpath <- "onlylog2"
  nrCluster <- 10

  print("ONLY log2 transform intensities.")
  tr <- lfqd$get_Transformer()
  tr$intensity_array(log2)
  transformed <- tr$lfq
  
  ag <- transformed$get_Aggregator()
  ag$medpolish()
  prot <- ag$lfq_agg
  
}else if (FALSE) {
  outpath <- "log2scaled"
  
  nrCluster <- 10

  print("log2 transform and scale intensities")
  tr <- lfqd$get_Transformer()
  transformed <- tr$log2_robscale()
  ag <- transformed$get_Aggregator()
  ag$medpolish()
  prot <- ag$lfq_agg
  tr <- prot$get_Transformer()
  tr$intensity_matrix(.func = prolfqua::robust_scale)
  prot <- tr$lfq

} else {
  outpath <- "creatinelog2"
  
  nrCluster <- 10

  print("adjust for ceratin level (intensitynew = intensity * mean(CmgdL)/ CmgdL")
  bb <- readxl::read_xlsx("O_22513/Creatinine_concentrations_.xlsx")
  colnames(bb) <- make.names(colnames(bb))
  bb <- bb %>% mutate(nf = mean(Creatinine.mg.dL.)/Creatinine.mg.dL.)
  bb <- inner_join(lfqd$data, bb, by = c("timeN" = "Samples.number"))
  bb <- bb %>% mutate(norm.pep.intensity = peptide.intensity*nf )
  lfqd$data <- bb
  lfqd$config$table$setWorkIntensity("norm.pep.intensity")
  
  tr <- lfqd$get_Transformer()
  lfqd$get_Plotter()$intensity_distribution_density()
  tr$intensity_array(log2)
  transformed <- tr$lfq
  transformed$get_Plotter()$intensity_distribution_density()
  ag <- transformed$get_Aggregator()
  ag$medpolish()
  prot <- ag$lfq_agg
}

pl <- prot$get_Plotter()
pl$intensity_distribution_density()
pNa <- pl$NA_heatmap()
p <- pl$heatmap()
pc <- pl$heatmap_cor()
```

```{r fig.width=10, fig.height=10, fig.cap="Heatamp based on presence and absence (black) of protein measurments"}
print(pNa)
```


```{r fig.width=10, fig.height=10, fig.cap = "Heatmap with color coded protein intensities"}
print(p)
```

```{r fig.cap="PCA plot"}
pl$pca()

```

# Cluster proteins

```{r fig.cap= "Clustering dendrogram of proteins"}
wide <- prot$to_wide(as.matrix = TRUE)
mdata <- wide$data
na <- apply(mdata, 1, function(x){sum(is.na(x))})
mdata <- mdata[na < 6,]
scaledM <- t(scale(t(mdata)))

```

Compute distances with jackknife

```{r jackknife, fig.width=10, fig.height=10}

dist_JK <- function(scaledM){
  alldst <- list()
  
  for (i in 1:ncol(scaledM)) {
    alldst[[i]] <- dist(scaledM[,-i])
  }
  
  xx <- Reduce("cbind",alldst)
  xx <- matrixStats::rowMedians(xx, na.rm = TRUE)
  res <- dist(scaledM)
  res[1:length(res)] <- xx
  return(res)
}

#distJK <- distJK(scaledM)
distJK <- dist_JK(scaledM)
attributes(distJK)
length(distJK)
saveRDS(distJK, file = "distJK.rda")
saveRDS(as.matrix(distJK), file = "fullMatrix.rda")



bb <- hclust(distJK)
k <- cutree(bb, k = nrCluster)

library(dendextend)
dend <- as.dendrogram(bb)
# Like: 

dend1 <- color_branches(dend, clusters = k[order.dendrogram(dend)], groupLabels = TRUE) %>% set("labels_cex", 0.2)
plot(dend1, main = "Dendrogram Dist JK")

```

```{r fig.width=10, fig.height=10, fig.cap = "X axis - time, Y axis - relative protein intensities. light gray line - profiles of a protein, black line - mean relative protein intensity of cluster"}

plotK <- function(scaledM, k , idx ){
  scM <- scaledM[ k == idx,, drop=FALSE]
  matplot(t(scM), col = "lightgray", type = "l", main = paste0("cluster ", idx))
  lines(1:13, apply(scM,2, mean, na.rm = TRUE), lwd = 2 )
  return(scM)
}

res <- list()
par(mfrow = c(2, nrCluster/2))
for (i in 1:nrCluster) {
  res[[i]] <- plotK(scaledM, k, i)
}

```


```{r mapIDs}
mapthe <- function(scaledM, cluster){
  background <- data.frame(SW = rownames(scaledM))
  cluster <- data.frame(SW = rownames(cluster))
  background <- prora::get_UniprotID_from_fasta_header(background, idcolumn = "SW")
  cluster <- prora::get_UniprotID_from_fasta_header(cluster, idcolumn = "SW")
  background <- prora::map_ids_uniprot(background)
  cluster <- prora::map_ids_uniprot(cluster)
  return(list(background = na.omit(background), cluster = na.omit(cluster)))
}


library(clusterProfiler)
library(org.Hs.eg.db)

mres <- list()
for (i in 1:length(res) ) {
  mres[[i]] <- mapthe(scaledM, res[[i]])
  mres[[i]]$cluster$cluster <- i
}
proteinsInCluster <- bind_rows(purrr::map(mres,"cluster"))

writexl::write_xlsx(proteinsInCluster, path = paste0("O_22513/",outpath,"ProteinsInClusters.xlsx"))
writexl::write_xlsx(mres[[1]]$background, path = paste0("O_22513/",outpath,"Background.xlsx"))
```

```{r compareClusters}
bb <- map(mres, "cluster") 
bb <- map(bb,"P_ENTREZGENEID")
names(bb) <- paste0("cluster ",1:nrCluster)
bb <- lapply(bb, as.character)
runGO <- TRUE
```

## GO Biological Process


```{r compareClustersBP, fig.height=5, fig.width=10, eval = runGO}
mt <- "GO Biological Process"
x <- compareCluster(bb,
               fun = "enrichGO",
               OrgDb =  org.Hs.eg.db,
               ont = "BP",
               universe = as.character( mres[[1]]$background$P_ENTREZGENEID),
               pvalueCutoff = 1,
               qvalueCutoff = 0.2,
               pAdjustMethod = "BH")

dotplot(x,title = mt)
DT::datatable(as.data.frame(x),caption = mt)
```

## GO Molecular Function

```{r compareClustersMF,  fig.height=5, fig.width=10, eval=runGO}
mt <- "GO Molecular Function"
x <- compareCluster(bb,
               fun = "enrichGO",
               OrgDb =  org.Hs.eg.db,
               ont = "MF",
               universe = as.character( mres[[1]]$background$P_ENTREZGENEID),
               pvalueCutoff = 1,
               qvalueCutoff = 0.2,
               pAdjustMethod = "BH")

dotplot(x,title = mt)
DT::datatable(as.data.frame(x),caption = mt)
```

# GO Cellular Component

```{r compareClustersCC,  fig.height=5, fig.width=10, eval=runGO}
mt <-  "GO Cellular Component"
x <- compareCluster(bb,
               fun = "enrichGO",
               OrgDb =  org.Hs.eg.db,
               ont = "CC",
               universe = as.character( mres[[1]]$background$P_ENTREZGENEID),
               pvalueCutoff = 1,
               qvalueCutoff = 0.2,
               pAdjustMethod = "BH")

dotplot(x,title = mt)
DT::datatable(as.data.frame(x),caption = mt)
```


```{r analyseAllclusters, eval=FALSE, include = FALSE, eval=FALSE}
gores <- list()
for (i in 1:length(mres)) {
  mrr <- mres[[i]]
  tmp <- enrichGO(as.character(mrr$cluster$P_ENTREZGENEID),
                  universe = as.character(mrr$background$P_ENTREZGENEID),
                  OrgDb         = org.Hs.eg.db,
                  ont           = "MF",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 1,
                  qvalueCutoff  = 1,
                  readable      = TRUE)
  dftmp <- as.data.frame(tmp)
  dftmp$cluster <- i
  gores[[i]] <- dftmp
}

allres <- bind_rows(gores)
dim(allres)


significant <- allres  %>% filter(p.adjust < 0.2) 
library(DT)
DT::datatable(significant)

```



